# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10e7f5614d4d01b2ea1071e5fd6521ed"
application_url = "https://helpful-evaluate-decent-popularity.trycloudflare.com"
embedded = true
name = "tay-test"
handle = "tay-test"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://helpful-evaluate-decent-popularity.trycloudflare.com/auth/callback",
  "https://helpful-evaluate-decent-popularity.trycloudflare.com/auth/shopify/callback",
  "https://helpful-evaluate-decent-popularity.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "tay-dev-ar6.myshopify.com"
automatically_update_urls_on_dev = true
